apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: web
      image: evilbox/otus_k8s:05.04.2021
      #imagePullPolicy: Always
      volumeMounts:
        - name: app
          mountPath: /app
  initContainers:
    - name: web-init
      securityContext:
        runAsNonRoot: true
        runAsGroup: 101
        runAsUser: 1001
      image: busybox:1.33.0-uclibc
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
